# Generated by Django 4.1.4 on 2023-02-10 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal_title', models.CharField(max_length=50)),
                ('journal_body', models.TextField()),
                ('journal_time_stamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SeedList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sun_requirements', models.CharField(choices=[('full-sun', 'Full Sun'), ('partial-sun', 'Partial Sun'), ('shade', 'Shade')], default='full-sun', max_length=20)),
                ('sow_method', models.CharField(choices=[('start-indoors', 'Start Indoors'), ('sow-direct', 'Sow Directly')], default='sow-direct', max_length=20)),
                ('seed_name', models.CharField(max_length=50)),
                ('seed_description', models.TextField()),
                ('days_till_harvest', models.PositiveSmallIntegerField()),
                ('plant_spacing', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
