# Generated by Django 4.1.4 on 2023-02-08 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_todolist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='description',
        ),
    ]
